http:
  routers:
    mt:
      rule: Host(`mt.trialworks.jp`)
      entryPoints:
        - web
      middlewares:
        - mt-https-redirect
      service: noop@internal

    mt-secure:
      rule: Host(`mt.trialworks.jp`)
      entryPoints:
        - websecure
      service: mt-service
      tls:
        certResolver: le

    oos:
      rule: Host(`oos.trialworks.jp`)
      entryPoints:
        - web
      service: oos-service

  services:
    mt-service:
      loadBalancer:
        servers:
          - url: http://mt-web:80

    oos-service:
      loadBalancer:
        servers:
          - url: http://oos-nginx-1:80

  middlewares:
    mt-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
